version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "8008:11434"
    restart: unless-stopped

  mega-service:
    build: ./mega-service
    ports:
      - "8000:8000"
    depends_on:
      - ollama
